{{- if .Values.externalSecrets.enabled -}}
{{- $root := . -}}
{{- range .Values.externalSecrets.items }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels:
    {{- include "nexus-hive.labels" $root | nindent 4 }}
spec:
  refreshInterval: {{ $root.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $root.Values.externalSecrets.secretStoreRef.name }}
    kind: {{ $root.Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range $envName, $remoteRef := .remoteKeys }}
    - secretKey: {{ $envName }}
      remoteRef:
        key: {{ splitList "#" $remoteRef | first }}
        property: {{ splitList "#" $remoteRef | last }}
    {{- end }}
{{- end }}
{{- end }}
