apiVersion: v1
kind: Service
metadata:
  name: nexus-hive-service
  namespace: nexus-hive
  labels:
    app.kubernetes.io/name: nexus-hive
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexus-hive
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
